// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3BqRs7qbq7zMbsXejm5mKQSwdriauZg4',
    appId: '1:204243442509:web:ef1d387f588218b147f504',
    messagingSenderId: '204243442509',
    projectId: 'chat-app-ab44a',
    authDomain: 'chat-app-ab44a.firebaseapp.com',
    storageBucket: 'chat-app-ab44a.appspot.com',
    measurementId: 'G-RNY4YYK8VT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpqDuU0t-qW3jj4TPW7XVnQo-r03_Z0w',
    appId: '1:204243442509:android:21c3a5a35c8ee3bd47f504',
    messagingSenderId: '204243442509',
    projectId: 'chat-app-ab44a',
    storageBucket: 'chat-app-ab44a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFwW3JdfQ2-605oPptQWtGoU_Rx7IZupQ',
    appId: '1:204243442509:ios:6269701011d7b94b47f504',
    messagingSenderId: '204243442509',
    projectId: 'chat-app-ab44a',
    storageBucket: 'chat-app-ab44a.appspot.com',
    iosClientId: '204243442509-80i0jia3onknut04b31b0ggo6v2fmbb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFwW3JdfQ2-605oPptQWtGoU_Rx7IZupQ',
    appId: '1:204243442509:ios:6269701011d7b94b47f504',
    messagingSenderId: '204243442509',
    projectId: 'chat-app-ab44a',
    storageBucket: 'chat-app-ab44a.appspot.com',
    iosClientId: '204243442509-80i0jia3onknut04b31b0ggo6v2fmbb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
